# 前期准备

## yarn

### 安装

1.有node.js环境

2.在[yarn中文网](https://yarn.bootcss.com/docs/install/#windows-stable)下载.msi文件，一路next安装

3.在终端中`npm i yarn -g`

通过`yarn --version`查看yarn版本，如有，则成功；若显示错误，可以以管理员模式打开vscode

### 命令

[yarn基本命令](https://blog.csdn.net/ZXW_Future/article/details/106583502)

初始化

`yarn init -y`

安装包

`yarn add webpack`

### 配置文件

package.json

```javascript
{
  "name": "async",
  "version": "0.1.0",
  "main": "index.js",
  "author": "wanglei",
  "license": "MIT",
  "dependencies": {
    "html-webpack-plugin": "^4.3.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  }
}

```

在项目目录的package.json同级目录下创建 webpack.config.js作为配置文件。

```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin')
module.exports = {
  mode: 'none',
  stats: 'none',
  devtool: 'source-map',
  plugins: [
    new HtmlWebpackPlugin()
  ]
}
```

### 运行

```javascript
yarn webpack-dev-server 01-promise.js --open
```

# Promise

## 例子

```javascript
// Promise 基本示例

const promise = new Promise(function (resolve, reject) {
    // 这里用于“兑现”承诺

    resolve(100) // 承诺达成

    // reject(new Error('promise rejected')) // 承诺失败
})

let r = promise.then(function (value) {
    // 即便没有异步操作，then 方法中传入的回调仍然会被放入队列，等待下一轮执行
    console.log('resolved', value)
}, function (error) {
    console.log('rejected', error)
})

console.log('end')
console.log('r')
```

```javascript
yarn webpack-dev-server 01-promise.js --open
//结果如下,then默认返回值为undefined的Promise
```

![1592543363698](C:\Users\wanglei\AppData\Roaming\Typora\typora-user-images\1592543363698.png)

## 封装ajax

```javascript
function ajax (url) {
    return new Promise((resolve,reject) => {
        var xhr = new XMLHttpRequest()
        xhr.open('GET', url)
        xhr.responseType = 'json'
        //H5新函数，相当于onReadyState = 4
        xhr.onload = function () {
            if (this.status === 200) {
                resolve(this.response)
            } else {
                reject(new Error(this.statusText))
            }
        }
        xhr.send()
    })
}

ajax('./api/users.json')
.then((res) => {
    console.log(res)
})
.catch((err) => {
    console.log(err)
})

ajax('./api/user.json')//不存在的路径
.then((res) => {
    console.log(res)
})
.catch((err) => {
    console.log(err)
})
```

![1592530817545](C:\Users\wanglei\AppData\Roaming\Typora\typora-user-images\1592530817545.png)

## 链式调用

- Promise 对象的 then 方法**默认**返回一个 **全新的 值为 undefined 的 Promise 对象**

- 也可以手动返回一个 Promise 对象

- 后面的 then 方法是在为上一个 then 返回的 Promise 注册 状态明确后的 回调

- **返回值不是 Promise ，那么依旧返回一个Promise 对象**，只是 Promise 的值为这个普通值，这个值也是后面 then 方法回调的参数

  return xxx 相当于：

  ```javascript
  return new Promise((resolve,reject) => {
      resolve(xxx)
  })
  ```

- 返回值是 Promise ，那后面的 then 方法的回调会等待它的结束

## catch

在 promise 异常、或失败都会执行 onRejected / catch

作用：可以捕获异常，Promise内部错误，或手动`throw new Error()`和手动`reject('参数，可以是任意值，常用是new Error(xxx)')`也可以捕获异常

**！！！catch只捕获第一个遇到的异常/错误**



**catch 实现原理：就是 then 方法**，参数来自reject()或错误信息

```javascript
.then(undefined, function onRejected (error) {
    console.log('onRejected', error)
})
```



如下，这种方法，**onRejected 只能捕获当前Promise对象抛出的异常**

```javascript
ajax('/api/users11.json')//地址错误，可以捕获
.then(function onFulfilled (value) {
console.log('onFulfilled', value)//如果这里出现异常，捕获不到
}, function onRejected (error) {
console.log('onRejected', error)
})
```

**而链式调用，调用 catch 的是前一个 then 返回的 Promise 对象**

```javascript
ajax('/api/users11.json')
.then(function onFulfilled (value) {
console.log('onFulfilled', value)//如果这里出现异常，能捕获到，因为返回的Promise会沿着链，一直往下传递，直到遇到catch
})
.catch(function onRejected (error) {//是给整条链（在此catch之前）注册异常处理
console.log('onRejected', error)
})
```



**catch 参考then，也默认返回一个Promise，状态resolved，值undefined**

除非在 catch 里`throw new Error('promise rejected')`，这样返回的 Promise 状态是 rejected

## 静态方法

最早用的是第三方库，引进 Promise 对象，现在可以把它转换成原生 Promise 

### Promise.resolve()

```javascript
Promise.resolve('foo')
.then((value) => {
    console.log(value) //foo
})
//等价于，其实就是then方法return值时 调用的函数
new Promise((resolve, reject) => {
    resolve('foo')
})

// 如果传入的是一个 Promise 对象，Promise.resolve 方法原样返回

var promise = new Promise((resolve, reject) => {
    resolve('foo')
})
var promise2 = Promise.resolve(promise)
console.log(promise === promise2) //true

// 如果传入的是带有一个跟 Promise 一样的 then 方法的对象，
// Promise.resolve 会将这个对象作为 Promise 执行

Promise.resolve({
  then: function (onFulfilled, onRejected) {
    onFulfilled('foo')
  }
})
.then(function (value) {
  console.log(value) //foo
})

```

### Promise.reject()

```javascript
// Promise.reject 传入任何值，都会作为这个 Promise 失败的理由

Promise.reject(new Error('rejected'))
  .catch(function (error) {
    console.log(error) //Error: rejected
  })

Promise.reject('anything')
  .catch(function (error) {
    console.log(error) //anything
  })
```

## 并行执行

在页面请求资源时，各个请求无依赖关系（先后顺序），我只想让所有的请求完毕后，开始渲染页面，如何做到呢？

传统方法：开个计数器，每个请求完毕计数器+1

现在方法：`Promise.all`

### Promise.all

同步执行多个 Promise ，返回一个 Promise ，

全部成功时：返回 Promise 的值是 传进来的的Promise数组 的**resolve 值 组成的数组，顺序与传进来的 Promise 顺序相同！**

有一个失败时：返回 Promise 的值是 **最先被 reject 的值**，也就是 reject(xxx) ，返回 xxx

```javascript
var promise = Promise.all([
  ajax('./api/users.json'),
  ajax('./api/posts.json')
])

console.log('all',promise)//Promise，值是数组

promise.then(function (values) {
  console.log(values)//输出数组
}).catch(function (error) {
  console.log(error)
})

ajax('/api/urls.json')
  .then(value => {
    const urls = Object.values(value)
    const tasks = urls.map(url => ajax(url))
    return Promise.all(tasks)//Promise，值是数组
  })
  .then(values => {
    console.log(values)//输出数组
  })
//成功结果如下
```

![1592568906764](C:\Users\wanglei\AppData\Roaming\Typora\typora-user-images\1592568906764.png)

```javascript
var promise = Promise.all([
  ajax('./api/users.json'),
  ajax('./api/posts.json'),
  Promise.reject('失败')
])

setTimeout(() => {
    console.log('all',promise)
},1000)

promise.then(function (values) {
  console.log(values)
}).catch(function (error) {
  console.log(error)
})
```

![1592569123985](C:\Users\wanglei\AppData\Roaming\Typora\typora-user-images\1592569123985.png)

### Promise.race

顾名思义，Promse.race就是赛跑的意思，意思就是说，Promise.race([p1, p2, p3])里面**哪个结果获得的快，就返回那个结果，不管结果本身是成功状态还是失败状态。**

```javascript
let p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  },1000)
})

let p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('failed')
  }, 500)
})

Promise.race([p1, p2])
.then((result) => {
  console.log(result)
})
.catch((error) => {
  console.log(error)  // 输出的是 'failed'
})
```

# Generator

Promise 链式调用，还是存在大量回调函数

为了解决这个问题，提高可读性，提出 Generator，更加扁平化，现在不用了

```javascript
function ajax(url) {
    return new Promise(function (resolve, reject) {
        // foo()
        // throw new Error()
        var xhr = new XMLHttpRequest()
        xhr.open('GET', url)
        xhr.responseType = 'json'
        xhr.onload = function () {
            if (this.status === 200) {
                resolve(this.response)
            } else {
                reject(new Error(this.statusText))
            }
        }
        xhr.send()
    })
}
function * main () {
    try {
        const users = yield ajax('/api/users.json')
        console.log(users)

        const posts = yield ajax('/api/posts.json')
        console.log(posts)

        const urls = uield ajax('/api/urls11.json')
        console.log(urls)
    } catch (e) {
        console.log(e)
    }
}

function co (generator) {
    const g = generator()

    function handleResult (result) {
        if(result.done) return //结束
        result.value.then(data => {
            handleResult(g.next(data))
        }, error => {
            g.throw(error)
        })
    }

    handleResult(g.next())
}

co(main)
```



# Async/Await

- 把 Generator 改造，不再需要 co 执行器，是语法糖
- 返回一个 Promise 对象

```javascript
async function main () {
    try {
        const users = await ajax('/api/users.json')
        console.log(users)

        const posts = await ajax('/api/posts.json')
        console.log(posts)

        const urls = await ajax('/api/urls11.json')
        console.log(urls)
    } catch (e) {
        console.log(e)
    }
}

const promise = main()

promise.then(() => {
    console.log('all completed')
})
```

# 测试-错误题

***1.为什么可以将非函数参数传给 Promise.then() ?**

![1592574798360](C:\Users\wanglei\AppData\Roaming\Typora\typora-user-images\1592574798360.png)

[为什么可以将非函数参数传给Promise.then()且不会产生错误](https://www.it1352.com/1010600.html)